package com.hybridtrader.v36monitor

import android.content.ContentValues
import android.content.Context
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class Db private constructor(ctx: Context) : SQLiteOpenHelper(ctx, "v36monitor.db", null, 1) {
 companion object {@Volatile private var inst:Db?=null;fun get(ctx:Context):Db=inst?:synchronized(this){inst?:Db(ctx.applicationContext).also{inst=it}}}
 override fun onCreate(db:SQLiteDatabase){db.execSQL("CREATE TABLE candles(open_time INTEGER PRIMARY KEY, open REAL NOT NULL, high REAL NOT NULL, low REAL NOT NULL, close REAL NOT NULL, volume REAL, close_time INTEGER NOT NULL, closed INTEGER NOT NULL)");db.execSQL("CREATE TABLE signals(id TEXT PRIMARY KEY, candle_time INTEGER NOT NULL, close_time INTEGER, type TEXT NOT NULL, entry REAL, regime TEXT, classification TEXT, stop REAL, target REAL, qty REAL, notional REAL, status TEXT, result TEXT, pnl REAL, r_multiple REAL, exit_time INTEGER, exit_price REAL, notification_sent INTEGER NOT NULL DEFAULT 0, created_at INTEGER, UNIQUE(candle_time, type))")}
 override fun onUpgrade(db:SQLiteDatabase,oldVersion:Int,newVersion:Int){}
 fun upsertCandles(list:List<Candle>){if(list.isEmpty())return;val db=writableDatabase;db.beginTransaction();try{val st=db.compileStatement("INSERT OR REPLACE INTO candles(open_time,open,high,low,close,volume,close_time,closed) VALUES(?,?,?,?,?,?,?,?)");for(k in list){st.clearBindings();st.bindLong(1,k.openTime);st.bindDouble(2,k.open);st.bindDouble(3,k.high);st.bindDouble(4,k.low);st.bindDouble(5,k.close);st.bindDouble(6,k.volume);st.bindLong(7,k.closeTime);st.bindLong(8,if(k.closed)1L else 0L);st.executeInsert()};db.setTransactionSuccessful()}finally{db.endTransaction()}}
 fun loadCandles():List<Candle>{val out=ArrayList<Candle>();readableDatabase.rawQuery("SELECT open_time,open,high,low,close,volume,close_time,closed FROM candles ORDER BY open_time",null).use{c->while(c.moveToNext())out.add(Candle(c.getLong(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5),c.getLong(6),c.getLong(7)==1L))};return out}
 fun latestOpenTime():Long?=readableDatabase.rawQuery("SELECT MAX(open_time) FROM candles",null).use{c->if(c.moveToFirst()&&!c.isNull(0))c.getLong(0) else null}
 fun hasClosedCandle(openTime:Long):Boolean=readableDatabase.rawQuery("SELECT 1 FROM candles WHERE open_time=? AND closed=1",arrayOf(openTime.toString())).use{it.moveToFirst()}
 fun openTimes():List<Long>{val out=ArrayList<Long>();readableDatabase.rawQuery("SELECT open_time FROM candles ORDER BY open_time",null).use{c->while(c.moveToNext())out.add(c.getLong(0))};return out}
 fun saveSignals(list:List<TradeSignal>,now:Long){if(list.isEmpty())return;val db=writableDatabase;db.beginTransaction();try{for(s in list){val cv=ContentValues();cv.put("id",s.id);cv.put("candle_time",s.candleTime);cv.put("close_time",s.closeTime);cv.put("type",s.type);cv.put("entry",s.entry);cv.put("regime",s.regime);cv.put("classification",s.classification);cv.put("stop",s.stop);putD(cv,"target",s.target);cv.put("qty",s.qty);cv.put("notional",s.notional);cv.put("status",s.status);cv.put("notification_sent",0);cv.put("created_at",now);db.insertWithOnConflict("signals",null,cv,SQLiteDatabase.CONFLICT_IGNORE);val up=ContentValues();up.put("status",s.status);if(s.result==null)up.putNull("result")else up.put("result",s.result);up.put("pnl",s.pnl);up.put("r_multiple",s.rMultiple);up.put("exit_time",s.exitTime);putD(up,"exit_price",s.exitPrice);db.update("signals",up,"id=?",arrayOf(s.id))};db.setTransactionSuccessful()}finally{db.endTransaction()}}
 private fun putD(cv:ContentValues,key:String,v:Double){if(v.isNaN())cv.putNull(key)else cv.put(key,v)}
 fun unsent():List<TradeSignal>{val out=ArrayList<TradeSignal>();readableDatabase.rawQuery("SELECT id,candle_time,close_time,type,entry,regime,classification,stop,target,qty,notional,status,result,pnl,r_multiple,exit_time,exit_price,notification_sent,created_at FROM signals WHERE notification_sent=0 ORDER BY candle_time",null).use{c->while(c.moveToNext())out.add(read(c))};return out}
 fun markSent(id:String){val cv=ContentValues();cv.put("notification_sent",1);writableDatabase.update("signals",cv,"id=?",arrayOf(id))}
 private fun read(c:Cursor)=TradeSignal(id=c.getString(0),candleTime=c.getLong(1),closeTime=c.getLong(2),type=c.getString(3),entry=c.getDouble(4),regime=c.getString(5),classification=c.getString(6),stop=c.getDouble(7),target=if(c.isNull(8))Double.NaN else c.getDouble(8),qty=c.getDouble(9),notional=c.getDouble(10),status=c.getString(11),result=if(c.isNull(12))null else c.getString(12),pnl=c.getDouble(13),rMultiple=c.getDouble(14),exitTime=c.getLong(15),exitPrice=if(c.isNull(16))Double.NaN else c.getDouble(16),notificationSent=c.getInt(17)==1,createdAt=c.getLong(18))
}